import{a as g,S as h,i as u}from"./assets/vendor-c493984e.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const v="44649550-1f14fff39212e3f1a5e911ecf",b="https://pixabay.com/api/",d=15;let l=1;async function f(o){const t={key:v,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:l,per_page:d};try{const s=await g.get(b,{params:t}),{hits:i,totalHits:e}=s.data;return l+=1,{hits:i,totalHits:e}}catch(s){console.log(s)}}function L(){l=1}function _({webformatURL:o,largeImageURL:t,tags:s,likes:i,views:e,comments:r,downloads:a}){return`<li class="item">
      <a href="${t}" class="gallery">
      <img class='item-img' src="${o}" alt="${s}" />
      <div class="item-info">
      <div class="item-info__text">Likes <span>${i}</span></div>
      <div class="item-info__text">Views <span>${e}</span></div>
      <div class="item-info__text">Comments <span>${r}</span></div>
      <div class="item-info__text">Downloads <span>${a}</span></div>
      </div>
      </a>
      </li>`}function m(o){const t=o.map(_).join("");n.imgOut.insertAdjacentHTML("beforeend",t)}function w(o){o.innerHTML=" "}const n={form:document.querySelector(".form-request"),imgOut:document.getElementById("img-output"),loader:document.querySelector(".loader"),moreBtn:document.querySelector(".action__button")};n.form.addEventListener("submit",O);n.moreBtn.addEventListener("click",q);const p=new h(".list a",{captions:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250});let c=null;async function O(o){if(o.preventDefault(),c=o.target.searchQuery.value.trim(),!c){u.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}try{L();const t=await f(c);w(n.imgOut),m(t.hits),y(),B()}catch(t){console.error(t)}finally{n.form.reset(),n.loader.style.display="none",p.refresh()}}async function q(){n.loader.style.display="block";try{const{hits:o,totalHits:t}=await f(c);m(o),l*d>=t&&(u.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),P()),y()}catch{console.error(error)}finally{n.loader.style.display="none",p.refresh()}}function B(){n.moreBtn.style.display="block"}function P(){n.moreBtn.style.display="none"}function y(){const o=document.querySelector(".list");if(console.log(o),o){const t=o.getBoundingClientRect().height;console.log(t),window.scrollBy({top:t*2,behavior:"smooth"})}}
//# sourceMappingURL=commonHelpers.js.map
