import{a as y,S as g,i as u}from"./assets/vendor-c493984e.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const h="44649550-1f14fff39212e3f1a5e911ecf",v="https://pixabay.com/api/",d=15;let l=1;async function f(r){const t={key:h,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:l,per_page:d};try{const n=await y.get(v,{params:t}),{hits:i,totalHits:e}=n.data;return l+=1,{hits:i,totalHits:e}}catch(n){console.log(n)}}function b(){l=1}function L({webformatURL:r,largeImageURL:t,tags:n,likes:i,views:e,comments:o,downloads:a}){return`<li class="item">
      <a href="${t}" class="gallery">
      <img class='item-img' src="${r}" alt="${n}" />
      <div class="item-info">
      <div class="item-info__text">Likes <span>${i}</span></div>
      <div class="item-info__text">Views <span>${e}</span></div>
      <div class="item-info__text">Comments <span>${o}</span></div>
      <div class="item-info__text">Downloads <span>${a}</span></div>
      </div>
      </a>
      </li>`}function m(r){const t=r.map(L);s.imgOut.insertAdjacentHTML("beforeend",t)}function _(r){r.innerHTML=" "}const s={form:document.querySelector(".form-request"),imgOut:document.getElementById("img-output"),loader:document.querySelector(".loader"),moreBtn:document.querySelector(".action__button")};s.form.addEventListener("submit",O);s.moreBtn.addEventListener("click",P);const p=new g(".list a",{captions:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250});let c=null;async function O(r){if(r.preventDefault(),c=r.target.searchQuery.value.trim(),!c){u.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}try{b();const t=await f(c);_(s.imgOut),m(t.hits),q()}catch(t){console.error(t)}finally{s.form.reset(),s.loader.style.display="none",p.refresh()}}async function P(){s.loader.style.display="block";try{const{hits:r,totalHits:t}=await f(c);m(r),l*d>=t&&(u.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),w())}catch{console.error(error)}finally{s.loader.style.display="none",p.refresh()}}function q(){s.moreBtn.style.display="block"}function w(){s.moreBtn.style.display="none"}
//# sourceMappingURL=commonHelpers.js.map
